# If your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would
# contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.

baseURL: "https://yaniv.hatiel.com/"
# Or, if you prefer relative paths (often safer on Pages):
relativeURLs: false

title: "Yaniv Hatiel | Founder and Design Director of 01Architecture"



footer:
  text: "Â© [Yaniv Hatiel](https://yaniv.hatiel.com)"
  hideCopyright: false
  hideThemeAttribution: true



disableKinds:
  - taxonomy
  - taxonomyTerm


theme: [PaperMod]
publishDir: "docs"


caches:
  images:
    dir: ":cacheDir/images"

  
params:
  label:
    text: "Yaniv Hatiel | M.Arch"
  author: "Yaniv Hatiel"

  profileMode:
    enabled: false
    title: Yaniv Hatiel | Founder and Design Director of 01Architecture
    subtitle: "Founder of 01Architecture | Lecturer at SCE | Ex-ZHA, KPF, PLP"
    imageUrl: "images/icon/social-preview.png"
    imageTitle: Yaniv Hatiel
    imageWidth: 120
    imageHeight: 120
    buttons:
      - name: 01Architecture
        url: https://01architecture.com
      - name: Research
        url: https://01architecture.com/lab

  homeInfoParams:
    Title: "Yaniv Hatiel"
    Content: >
        I am the founder of [01Architecture](https://01architecture.com), a design and research studio focused on integrating computational tools, sustainability, and performance-driven strategies into architectural workflows.

        
        Previously, I worked as a Senior Designer at Zaha Hadid Architects, Project BIM Specialist at KPF, and Computational Designer at PLP Architecture.

  socialIcons:
    - name: Linkedin
      url: "https://www.linkedin.com/in/yanivhatiel/"
    - name: Email
      url: "mailto:yanivh@01architecture.com"
  description: "Yaniv Hatiel is the Founder and Design Director of 01Architecture, a London-based studio specializing in computational design, performance-driven architecture, and advanced geometry. Lecturer at SCE and former Senior Designer at Zaha Hadid Architects."
  keywords: ["Yaniv Hatiel", "01Architecture", "Computational Design", "Architect", "London", "Zaha Hadid Architects", "KPF", "Parametric Design", "BIM", "Generative Design"]



  
  assets:
  
    social_image: "images/icon/social-preview.png"
    customCSS:
      - css/custom.css
      - css/extended/high-end.css
    
    fingerprint: false
    disableHLJS: true
    
    ShowShareButtons: true
    ShowReadingTime: true
    ShowCodeCopyButtons: true

    defaultTheme: dark
    disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: true
    ShowAllPagesInArchive: true
    ShowPageNums: true
    ShowToc: true
    # comments: false
    images: ["images/icon/social-preview.png"]
    favicon: "images/icon/favicon.ico"
    favicon16x16: "images/icon/favicon-16x16.png"
    favicon32x32: "images/icon/favicon-32x32.png"
    apple_touch_icon: "images/icon/apple-touch-icon.png"
    safari_pinned_tab: "images/icon/safari-pinned-tab.svg"
    theme_color: "#ffffff"
    msapplication_TileColor: "#ffffff"
      
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["projects"]

minify:
  disableXML: true
  # minifyOutput: true

pagination:
  disableAliases: false
  pagerSize: 5

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: 01Architecture
          url: https://01architecture.com
          weight: 1
          params:
            target: "_blank"

        - name: Research
          url: https://01architecture.com/lab
          weight: 2
          params:
            target: "_blank"

        - name: About
          url: about
          weight: 4
          params:
            target: "_blank"
        
outputs:
  home:
    - HTML
    - RSS
    - JSON

  # analytics:
  #     google:
  #         SiteVerificationTag: "XYZabc"



  #     favicon: "<link / abs url>"
  #     favicon16x16: "<link / abs url>"
  #     favicon32x32: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"


  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

# privacy:
#   vimeo:
#     disabled: false
#     simple: true

#   twitter:
#     disabled: false
#     enableDNT: true
#     simple: true

#   instagram:
#     disabled: false
#     simple: true

#   youtube:
#     disabled: false
#     privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  x:
    disableInlineCSS: true
    
    
