backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

local_backend: true # Allow local editing without authentication

media_folder: "static/images" # Media files will be stored in the repo under static/images
public_folder: "/images" # The src attribute for uploaded media will begin with /images

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/about/index.md"
        label: "About Page"
        name: "about"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Subtitle", name: "subtitle", widget: "string"}
          - {label: "Experience Record", name: "projects", widget: "list", fields: [
              {label: "Project Name", name: "name", widget: "string"},
              {label: "Office", name: "office", widget: "string"},
              {label: "Status", name: "status", widget: "select", options: ["Built", "Under Construction", "Concept", "Masterplan"], required: false},
              {label: "Year", name: "year", widget: "string"},
              {label: "Location", name: "location", widget: "string"},
              {label: "Type", name: "type", widget: "string"},
              {label: "Area", name: "area", widget: "string"}
            ]}
          - {label: "Body", name: "body", widget: "markdown"}
